### ISSUE TITLE
Can't delete notes with Delete key MacOS

### ISSUE THREAD

**Issue by lacostenycoder** [8bitbubsy/ft2-clone#1]
The delete key doesn't seem to work.  Is there something I need to setup or change in system config?

**Comment by lacostenycoder** [comment]
It seems the note sometimes won't delete if your cursor is already on top of an existing note.  But if you go select an empty note after it, then delete seems to work.  Not sure if this is a bug or by design.

**Comment by 8bitbubsy** [comment]
I just tested this on my MacBook Pro, and it works like it should here. If your keyboard doesn't have the delete key, you need to use Fn+Backspace. I tested both Fn+Backspace on the internal keyboard and Delete on an external USB keyboard, and both worked fine with no bugs in note removal.

Could you give some more details? Are you in edit mode or record mode? Does it happen all the time (e.g. can you trigger the bug by opening the FT2 clone, entering some notes, then trying to delete them?). Also I assume that by "selecting" a note you mean to move the pattern cursor to it, and not _mark_ the note. Delete doesn't work on marked notes, but only on the current selected note (cursor).
