### ISSUE TITLE
Make CMakeLists.txt work on mac os too

### ISSUE THREAD

**Issue by fgaz** [8bitbubsy/ft2-clone#13]
In NixOS we use cmake to build this package, and I noticed that it'd only require a few CMakeLists.txt modifications to make it work on mac os too, namely:

* define `__MACOSX_CORE__` instead of `__LINUX_ALSA__` when building on mac os
* add the `-framework CoreAudio -framework CoreMIDI -framework CoreServices -framework Cocoa` linking flags when building on mac os (not sure how this is done in cmake)
* only link `asound` when building on linux

this would make it possible to drop the ad-hoc `make-*.sh` scripts

**Comment by 8bitbubsy** [comment]
I don't really know how to make makefiles, so someone else has to do this. Also it's important that CMakeLists.txt still works for Linux...

**Comment by fgaz** [comment]
> I don't really know how to make makefiles, so someone else has to do this

I know how to make basic makefiles, but I also don't really know cmake. On the NixOS package [I'm applying the mac fixes externally](https://github.com/NixOS/nixpkgs/pull/108167/commits/5ec0a5636e79ee16ea5f1a4022e77e5bd6a521b4). @OPNA2608 are you familiar with it and willing to give a hand? Otherwise I guess I can just dive into the docs and figure out something.

> Also it's important that CMakeLists.txt still works for Linux

This shouldn't be a problem if all of the above fixes are applied conditionally

**Comment by 8bitbubsy** [comment]
This has been fixed in the latest commit. Please let me know if it's still not correct!
