### ISSUE TITLE
Strange issue with ghost notes

### ISSUE THREAD

**Issue by herodotas** [8bitbubsy/ft2-clone#15]
Found strange issue: ghost note played pitched up. Too difficult to explain, but here mod in witch i found issue. Best to hear in  first
 pattern, track 3.  Tested in others trackers, including your protracker clone, all plays same not pitched sound.
[mod.zip](https://github.com/8bitbubsy/ft2-clone/files/5844975/mod.zip)

**Comment by 8bitbubsy** [comment]
Fasttracker II is not 100% ProTracker compatible, and this song is using several PT-specific quirks. This behavior is expected.
If I were to change it, then the XM accuracy in itself would also be messed with.
