### ISSUE TITLE
Missing files in `CMakeLists.txt`

### ISSUE THREAD

**Issue by jube** [8bitbubsy/ft2-clone#16]
Some files are missing in `CMakeLists.txt`. After adding these two lines, it works.
```
    "${ft2-clone_SOURCE_DIR}/src/modloaders/*.c"
    "${ft2-clone_SOURCE_DIR}/src/smploaders/*.c"
```

**Comment by 8bitbubsy** [comment]
Fixed, I tend to forget that this file is a makefile because of the .txt extension. Thanks for reporting it!

**Comment by jube** [comment]
Thanks for your amazing work on this clone!
