### ISSUE TITLE
wayland mouse offset

### ISSUE THREAD

**Issue by oskude** [8bitbubsy/ft2-clone#21]
on wayland, when using hardware mouse, the mouse click is not registered where the mouse cursor is.

i tinkered a bit and this could be a good fix:
```diff
diff --git a/src/ft2_video.c b/src/ft2_video.c
index 026a8e6..49b4f79 100644
--- a/src/ft2_video.c
+++ b/src/ft2_video.c
@@ -1006,10 +1006,10 @@ bool setupRenderer(void)
 	else
 		SDL_ShowCursor(SDL_FALSE);

-	// Workaround: SDL_GetGlobalMouseState() doesn't work with KMSDRM
+	// Workaround: SDL_GetGlobalMouseState() doesn't work with KMSDRM/Wayland
 	video.useDesktopMouseCoords = true;
 	const char *videoDriver = SDL_GetCurrentVideoDriver();
-	if (videoDriver != NULL && strcmp("KMSDRM", videoDriver) == 0)
+	if (videoDriver != NULL && (strcmp("KMSDRM", videoDriver) == 0 || strcmp("wayland", videoDriver) == 0))
 		video.useDesktopMouseCoords = false;

 	SDL_SetRenderDrawColor(video.renderer, 0, 0, 0, SDL_ALPHA_OPAQUE);

```

i've tested above change in:

- i3 (xorg)
- sway (wayland)
- weston (wayland)

and it seems to fix the issue (and not break on xorg).

**Comment by 8bitbubsy** [comment]
Thanks, nice and clean fix. I'll integrate it into the current code base. However, I'm not sure when I'll release a new version, it might not be any time soon...

**Comment by oskude** [comment]
no rush with release, i can build my packages easily from git :)
