### ISSUE TITLE
Support Android?  支持安卓？

### ISSUE THREAD

**Issue by TIAOPINGZHONGGUO** [8bitbubsy/ft2-clone#24]
尊敬的開發者大大：請問FT2可以順利的移植到移動安卓設備上嗎🤔？如果可以的話就讓他在移動設備上再次大放廣彩吧😊！

Dear developer: Can FT2 be successfully ported to mobile Android devices🤔? If possible, let him show off again on mobile devices😊!

**Comment by 8bitbubsy** [comment]
Probably not, the program is not designed for touch screens...

**Comment by TIAOPINGZHONGGUO** [comment]
Or add a virtual mouse just like in DOSBOX, change the keyboard to a virtual keyboard, or support MIDI input and output?

**Comment by TIAOPINGZHONGGUO** [comment]
![Uploading Screenshot_20210904_171735_bruenor.magicbox.jpg…]()

**Comment by TIAOPINGZHONGGUO** [comment]
![Screenshot_20210904_171735_bruenor magicbox](https://user-images.githubusercontent.com/84202693/132089931-798ca592-1469-487f-a517-593790fba6e2.jpg)

**Comment by 8bitbubsy** [comment]
Sorry, but it's too much work, I don't have experience with Android and touchscreen programming.

**Comment by 8bitbubsy** [comment]
I don't support mobile devices, the tracker clone is hardcoded for desktop usage.

**Comment by TIAOPINGZHONGGUO** [comment]
Excuse me, is this version of yours Android?

**Comment by 8bitbubsy** [comment]
No, sorry.
