### ISSUE TITLE
Ft2 clone crashes on copying sample/instruments

### ISSUE THREAD

**Issue by herodotas** [8bitbubsy/ft2-clone#25]
Hello, I try to copy sample or instrument using S.E.Ext and always get a crash. version 1.47 Win 10

**Comment by 8bitbubsy** [comment]
Thanks for the bug report, I can indeed reproduce the buggy behavior, and I'm currently investigating and going to release a new version when fixed.

**Comment by 8bitbubsy** [comment]
This issue was fixed, and v1.48 was just released! Please let me know if it works like it should for you now. It did for me, but I didn't test it in every way imaginable.

**Comment by herodotas** [comment]
Thanks for quick fix, seems everything works now!
