### ISSUE TITLE
Playback of MOD isn't correct... Tested on orig FT2 and it plays correctly...

### ISSUE THREAD

**Issue by ajack2001my** [8bitbubsy/ft2-clone#33]
[FARLAND.zip](https://github.com/8bitbubsy/ft2-clone/files/8148441/FARLAND.zip)

**Comment by 8bitbubsy** [comment]
Can you please specify where it fails?

**Comment by 8bitbubsy** [comment]
Sounds identical. Do yo use an old version of the FT2 clone?

**Comment by 8bitbubsy** [comment]
Result (tested against FT2.09): https://16-bits.org/etc/clone_then_real_ft2.mp3
For the testing, I set the FT2 clone to use linear interpolation.

**Comment by ajack2001my** [comment]
> Sounds identical. Do yo use an old version of the FT2 clone?

v2.08... Run on Win 10_x64

**Comment by ajack2001my** [comment]
> Result (tested against FT2.09): https://16-bits.org/etc/clone_then_real_ft2.mp3 For the testing, I set the FT2 clone to use linear interpolation. This makes it sound like real FT2 (although windowed-sinc interpolation is of higher quality).

Ran with default settings on both

**Comment by ajack2001my** [comment]
[ft2playback.zip](https://github.com/8bitbubsy/ft2-clone/files/8148485/ft2playback.zip)
This is the output I get...

**Comment by 8bitbubsy** [comment]
Ah. That's sample 6, not 7! I Apparently the loop point is not correct. I'll investigate.

**Comment by 8bitbubsy** [comment]
That's sample 5, not 6. So I was looking at the wrong sample... Anyway, it seems like its loop point is completely wrong. I'll investigate.

**Comment by ajack2001my** [comment]
> That's sample 5, not 6. So I was looking at the wrong sample... Anyway, it seems like its loop point is completely wrong. I'll investigate.

Sorry for the wrong info, my bad... :/

**Comment by 8bitbubsy** [comment]
No problem. Going to release a new version of the FT2 clone with the fix today.

**Comment by 8bitbubsy** [comment]
Ok, this has been fixed now. New version (v1.52) has been uploaded to https://16-bits.org/ft2.php

**Comment by ajack2001my** [comment]
Want to report your FT 2.11 for MS-DOS has the same problem... :p

**Comment by 8bitbubsy** [comment]
Yep, I'm actually aware after testing it, and it's a shame. Not sure if I'll fix it in silence and not change the version number, or if I should bother at all...

**Comment by ajack2001my** [comment]
> Yep, I'm actually aware after testing it, and it's a shame. Not sure if I'll fix it in silence and not change the version number, or if I should bother at all...

I'd suggest you fix it, version number isn't important... It is after all, the right thing to do. After you've put so much effort into this.

**Comment by 8bitbubsy** [comment]
Fixed: https://16-bits.org/etc/FT211.ZIP
