### ISSUE TITLE
I found original FT2 v2.04. UI Graphics viewed from 1994 (not from 1997)

### ISSUE THREAD

**Issue by Vad1mCSO2** [8bitbubsy/ft2-clone#34]
![image](https://user-images.githubusercontent.com/76803825/160745121-779c9ce8-1540-4b05-a8e0-9aed296f8115.png)
![image](https://user-images.githubusercontent.com/76803825/160745259-d1be73d3-9f49-4412-8bf2-440fa6c55ac2.png)
[ft204.zip](https://github.com/8bitbubsy/ft2-clone/files/8376783/ft204.zip)
[ft2logoby1994.zip](https://github.com/8bitbubsy/ft2-clone/files/8376789/ft2logoby1994.zip)

**Comment by 8bitbubsy** [comment]
Hi. Dumping the graphics from FT2 is not too complicated, but thanks anyway.

Also just in case you are interested, here's an archive of almost all FT2 versions (only FT2.02 missing, I think. FT2.07 was never released): https://16-bits.org/ft2/
