### ISSUE TITLE
Will ft2 support FM sound source in the future?

### ISSUE THREAD

**Issue by TIAOPINGZHONGGUO** [8bitbubsy/ft2-clone#35]
For example, take the first 16 channels as FM and the last 16 channels as PCM? Just like the chord mobile phone sound source equipped with YMU762MA-3 sound chip, FM timbre instruments can be customized? Will this idea come true?

**Comment by 8bitbubsy** [comment]
The FT2 clone is a _clone_ of Fasttracker II for MS-DOS. It will not support FM synthesis.
