### ISSUE TITLE
Link against LIBCMT.lib (/MT) instead of MSVCRT.lib (/MD)

### ISSUE THREAD

**Issue by a740g** [8bitbubsy/ft2-clone#37]
Hi @8bitbubsy

First I must congratulate your for the brilliant and excellent work you are doing.

I am sure you may have looked at this. However, I want to understand your choice of linking against the DLL version of MSCRT instead of the static version.

I see that you have a [text file](https://github.com/8bitbubsy/ft2-clone/blob/master/release/readme%20now.txt) explaining folks to download and install the `Microsoft Visual C++ Redistributable`. However, you could avoid this by just linking against `LIBCMT.lib` (`/MT`) in the VS Solution. This will allow you to get rid of the above text file and save your users one step.

**Comment by 8bitbubsy** [comment]
Simply because it causes way more false virus positives. I used to link the runtime in the earlier days.

**Comment by 8bitbubsy** [comment]
Most users don't have to do a thing, as they already have the runtime installed. Unless you're talking about old Windows, of course.

**Comment by a740g** [comment]
> Most users don't have to do a thing, as they already have the runtime installed. Unless you're talking about old Windows, of course.

Ok fair point. However, I ran into trouble when using this on an old version of Windows 10. Now I cannot recollect which version it was.

But the `false virus positive` thing is news to me.

Anyway, thank you for explaining. 👍
