### ISSUE TITLE
Volume slide up command key?

### ISSUE THREAD

**Issue by herodotas** [8bitbubsy/ft2-clone#38]
Hello,
can't find a key to enter "volume slide up" command in volume column. '+' nor "shift + '+'" not work for me. US keyboard layout.

**Comment by 8bitbubsy** [comment]
I made a workaround for this, where pressing the key to the left of backspace now works as '+'. This is not very intuitive, but it's better than nothing. You can download the new version (v1.61) from 16-bits.org.

Please let me know if it works for you.

**Comment by herodotas** [comment]
Works now! Thanks.
