### ISSUE TITLE
Invisible obstacles in nibbles

### ISSUE THREAD

**Issue by tomaes** [8bitbubsy/ft2-clone#4]
When setting the desktop color to black, all the obstacles in nibbles are invisible. Could be a case of "it's not a bug, it's a feature" (aka blind mode), but maybe a warning message would be nice if the desktop color/luminance is set too low to play without surprises. :)

**Comment by alexmyczko** [comment]
but did you find the trainer/cheat modes?

**Comment by tomaes** [comment]
@alexmyczko : I did. I was kinda surprised that there are/were any. (very helpful on lv28 ;)

There's also another bug with the hiscore thumbnail once you get to the end (and pass lv 30)

**Comment by 8bitbubsy** [comment]
Both of the issues have been fixed. Thanks.
