### ISSUE TITLE
[macOS] Add 2x/3x Scaling/Fullscreen for monitors larger than 640x400

### ISSUE THREAD

**Issue by lafoxxx92** [8bitbubsy/ft2-clone#41]
Actual:
![image](https://github.com/8bitbubsy/ft2-clone/assets/34402711/59fd5f2c-f7e5-4c9c-a0c7-59bc55ffdbe6)

Expected:
![image](https://github.com/8bitbubsy/ft2-clone/assets/34402711/03039c84-fd6a-4b70-90a3-b46bba02dfd5)
![image](https://github.com/8bitbubsy/ft2-clone/assets/34402711/f93ec071-2dbf-4bcc-8d04-aecc8d08c170)

This should make the product easier to use without need to lean very close to the screen
Liner interpolation optional (nearest doesn't look good in scales between 1x and 2x usually)

**Comment by 8bitbubsy** [comment]
If "Window size: Auto fit" doesn't work well, set it to 2x or 3x manually at Config -> Miscellaneous inside the program.
The reason auto-fit fails is because of the dock. It takes some headroom into account just for this, so it results in a too small image (1x or 2x) on some systems.
