### ISSUE TITLE
Pressing Space key will stop and start the Song

### ISSUE THREAD

**Issue by protektwar** [8bitbubsy/ft2-clone#43]
As I remember in FT2 by pressing the "space" key the Song will start or stop playing.

**Comment by 8bitbubsy** [comment]
Yes, and that's how it works in the FT2 clone as well.

**Comment by 8bitbubsy** [comment]
If it doesn't, then the space key is not handled in your case, for some reason. I just verified that it works in macOS using the latest version of the FT2 clone. Pretty sure it works fine on Windows as well.

**Comment by protektwar** [comment]
I have forgot to say I use it under Ubuntu 22.04 installed with apt.
Space key stops, CTRL key starts.

**Comment by 8bitbubsy** [comment]
Ah, I see what you mean. Stop won't start the song in FT2, only stop.
