### ISSUE TITLE
ALT + F3/F4/F5 not work in 1.71 on Windows

### ISSUE THREAD

**Issue by herodotas** [8bitbubsy/ft2-clone#44]
Hello,
ALT + F3/F4/F5 not work in 1.71 on Windows 11, older versions worked. Tried with GeForce Experience uninstalled, not work too.

**Comment by 8bitbubsy** [comment]
Right, I made a mistake in v1.71 for single-channel marks with ALT+F4 (Copy Block). This has been fixed. Will release a new version (v1.72) very soon.

**Comment by 8bitbubsy** [comment]
This was fixed just now. Thanks for reporting this!
