### ISSUE TITLE
weird behaviour with Touchscreen

### ISSUE THREAD

**Issue by ayskura** [8bitbubsy/ft2-clone#46]
I am using FT2 Clone with a Windows 8 tablet, and it works great except the touchscreen has one issue: when I touch to click, the click appears always in the last position I touched the screen, not the one I am currently touching. Basically if I touch twice in the same place it will click the button under the touchscreen, but if I try to touch something else, it always click first on the last position. A sort of workaround is to not click (touch) but drag and position where I want to click, then touch twice and goes ahead, which makes all the experience ultra slow and cumbersome. Is there a reason for this? I only have this issue with FT2 Clone and with PT2 Clone, all other app works as expected with touchscreen

thank you

**Comment by 8bitbubsy** [comment]
The FT2 (or PT2) clone is not designed for touchscreens, unfortunately.
