### ISSUE TITLE
Software mouse should be ON by default

### ISSUE THREAD

**Issue by malespiaut** [8bitbubsy/ft2-clone#48]
Hello,

I've recently tested the latest revision of ft2-clone on my machine. I'm running Arch Linux with the i3 window manager.

When ft2-clone uses the hardware mouse, the cursor position doesn't match with what I'm clicking on, if I do the following:

1) Running ft2-clone in windowed mode.
2) Going fullscreen by pressing Super+F.

Activating the software mouse fixes the issue… and it looks better in my humble opinion, since the cursor position have to be aligned with the pixels drawn on the screen.

**Comment by malespiaut** [comment]
I also must point out that this issue, and workaround, also affects pt2-clone.

**Comment by 8bitbubsy** [comment]
No, it should not be on by default, as it adds a frame of delay, and it limits the mouse to 60Hz on monitors running at higher refresh rates (like mine, which is at 240Hz).

I don't know why the coordinate translation fails on your system, it works fine on my PC, my Macs and my Ubuntu Linux test machine.

**Comment by malespiaut** [comment]
Wow! That was fast! Maybe there's something to optimise somewhere if software mouse adds a frame.

If you want to reproduce this behavior, I suppose that you could just set up a Arch Linux VM with only i3. But I'm not familiar enough with the code to understand what is causing this problem…

**Comment by 8bitbubsy** [comment]
There's nothing to optimize, it has to do with the nature of vsync with SDL2. I don't really support Linux for my tracker clones, as so many people have different problems depending on what distro, window manager and drivers they use. Sorry...
