### ISSUE TITLE
Is there anyway to make Insert work on a MacBook Pro?

### ISSUE THREAD

**Issue by ahku** [8bitbubsy/ft2-clone#49]
Fn+Enter doesn't work, unfortunately.

Is there any way to rebind the short keys somehow?

**Comment by JoNilsson** [comment]
This is something that has driven me mad as well.  I never found a way to succeed in getting MacOS to send the insert command.

If anyone knows,  it would be AWESOME to put if in a README.

**Comment by 8bitbubsy** [comment]
This has been rectified in the latest version
```
       Ctrl+Return       = Insert Note (same as Insert)
       Ctrl+Shift+Return = Insert Line (same as Shift+Insert)
```
