### ISSUE TITLE
Flickering time display in Extend mode

### ISSUE THREAD

**Issue by SyntaxErrol** [8bitbubsy/ft2-clone#54]
Hiyo, saw this on v1.85 on macOS 13.6.9:

![image](https://github.com/user-attachments/assets/75d5b1fd-6f88-4b45-853c-2e94532cf7d8)

Looks out of place with that desktop background color on the digits but what's more distracting is the flicker on pattern repaints.

**Comment by 8bitbubsy** [comment]
Oops, I forgot to render the status bar in extended pattern view mode if framework is disabled. Will fix this. Thanks!

**Comment by 8bitbubsy** [comment]
Fixed.
