### ISSUE TITLE
Fast Tracker 2 Clone crashes on launch, gives BSOD

### ISSUE THREAD

**Issue by Delicieuxz** [8bitbubsy/ft2-clone#8]
Hello. I tried to use a version FT2C that I downloaded many months ago. Whenever I would launch it, it would open a blank window which instantly crashed. And then a minute later, my Windows 10 64 OS would get a BSOD with the message IRQL_not_less_or_equal, and then my PC would reset. I tried the program multiple times and each time the same thing would happen.

I've now downloaded the latest version of FT2C. When I launch it, the program window loads, and it appears like it should (it isn't blank), but it still crashes within a second of launching. However, I don't get the BSOD as frequently with the latest version. I was able to launch it, and watch it crash, multiple times without getting the BSOD. But then on another launch it gave me the same BSOD. And after my PC restarted, I did the same thing: Launched it and watched it crash multiple times without getting a BSOD, but then on another try getting the BSOD after it crashed.

Attached is a photo of the BSOD. By the way, your ProTracker 2 clone hasn't crashed on launch or caused a BSOD on my system during the time that I've tested it out.

My system is running Windows 10 LTSC 1809 with 16 GB of RAM on an i7 2600k, and has an Auzentech Prelude sound card.

![FT2C BSOD](https://user-images.githubusercontent.com/69126253/89134810-eb12e880-d4dc-11ea-80fc-c41785a13f35.jpg)

**Comment by 8bitbubsy** [comment]
There's no way my program can cause a BSOD alone, you need a kernel-level problem for that to occur. It sounds like your system is unstable, or that you are using outdated drivers.

**Comment by 8bitbubsy** [comment]
I think you have a buggy (or incompatible with Windows 10) sound driver. Anyway, I compiled the FT2 clone without MIDI, just in case that stuff is triggering a bug in your sound card drivers. Can you test it?
https://www.dropbox.com/s/hgk2k97maa10j3w/ft2c_v127_nomidi.zip?dl=1

**Comment by Delicieuxz** [comment]
Hi. The Win32 build launches and works fine. The Win64 build crashes on launch as before, but it doesn't case a BSOD anymore.

I also just tried the latest official release's Win32 build, and it launches and works just fine. I hadn't tried the Win32 build before as it is labelled as not recommended on the downloads page ( https://16-bits.org/ft2.php ). How come it isn't recommended?

So, the crashing is specific to the Win64 build, and the BSOD issue is specific to the official release of the Win64 build.

**Comment by 8bitbubsy** [comment]
I don't recommend the 32-bit build because it's an ancient platform, and audio channel mixer in the FT2 clone is of slightly better quality in the 64-bit version (also supports higher mixing frequencies).
Anyway, I don't really know what to do about the crash and BSOD, it still sounds like something is unstable on your machine (or bad drivers). A BSOD comes from a hardware, kernel or driver problem.

**Comment by Delicieuxz** [comment]
The audio driver I'm using is an unofficial one made for Windows 10, and was released in 2017:
http://danielkawakami.blogspot.com/

It looks like a new version was released just yesterday, after 3.5 years. I might ask the person who makes the unofficial driver updates for my soundcard about the matter.

While it could be an issue with the audio driver, I have lots of audio editing programs on my PC and FT2 clone is currently the only one which is giving me a BSOD.

**Comment by 8bitbubsy** [comment]
The driver mentioned in your BSOD (ha20x2k.sys) is a Creative X-Fi driver, so it's pretty likely that this comes from a buggy sound driver.
