### ISSUE TITLE
TAB key puts cursor in a weird place when having more than 8 channels

### ISSUE THREAD

**Issue by aleksblendwerk** [8bitbubsy/ft2-clone#9]
How to reproduce: 

Start FT2 clone, add 2 channels (making it 10) and keep pressing TAB. On the last channel, the view does not wrap around to channel 1 and the cursor is stuck in a weird place in between channels 9 and 10.

Something like this (where the square brackets should represent the cursor):

```
CH9         CH10
--- -- 0[00 -]-- -- 000 
```

Note inputs then end up on channel 1.

This is with v1.28 on Win64.

**Comment by 8bitbubsy** [comment]
Thanks for mentioning this bug, I have commited a fix. Will release v1.29 very soon (I think this is important enough of a bugfix to get a new version).

**Comment by 8bitbubsy** [comment]
Release binaries uploaded. Please let me know if it's still not working correctly. :)
